
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 13 14:18:43 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menorigual = 18;
  public static final int parc = 13;
  public static final int para = 12;
  public static final int cadena = 5;
  public static final int decimal = 4;
  public static final int not = 22;
  public static final int pot = 11;
  public static final int por = 10;
  public static final int or = 15;
  public static final int caracter = 6;
  public static final int menos = 8;
  public static final int menor = 16;
  public static final int mayorigual = 19;
  public static final int EOF = 0;
  public static final int dividido = 9;
  public static final int noigual = 21;
  public static final int id = 2;
  public static final int error = 1;
  public static final int entero = 3;
  public static final int mas = 7;
  public static final int igualigual = 20;
  public static final int and = 14;
  public static final int mayor = 17;
}

